// src/components.d.ts
import { Field as FormField } from 'vee-validate'

declare module 'vue' {
  export interface GlobalComponents {
    AppAlertDialog: (typeof import('@/components/ui/alert-dialog/AlertDialog.vue'))['default']
    AppAlertDialogAction: (typeof import('@/components/ui/alert-dialog/AlertDialogAction.vue'))['default']
    AppAlertDialogCancel: (typeof import('@/components/ui/alert-dialog/AlertDialogCancel.vue'))['default']
    AppAlertDialogContent: (typeof import('@/components/ui/alert-dialog/AlertDialogContent.vue'))['default']
    AppAlertDialogDescription: (typeof import('@/components/ui/alert-dialog/AlertDialogDescription.vue'))['default']
    AppAlertDialogFooter: (typeof import('@/components/ui/alert-dialog/AlertDialogFooter.vue'))['default']
    AppAlertDialogHeader: (typeof import('@/components/ui/alert-dialog/AlertDialogHeader.vue'))['default']
    AppAlertDialogTrigger: (typeof import('@/components/ui/alert-dialog/AlertDialogTrigger.vue'))['default']
    AppAvatar: (typeof import('@/components/ui/avatar/Avatar.vue'))['default']
    AppAvatarFallback: (typeof import('@/components/ui/avatar/AvatarFallback.vue'))['default']
    AppAvatarImage: (typeof import('@/components/ui/avatar/AvatarImage.vue'))['default']
    AppCard: (typeof import('@/components/ui/card/Card.vue'))['default']
    AppBadge: (typeof import('@/components/ui/badge/Badge.vue'))['default']
    AppCheckbox: (typeof import('@/components/ui/checkbox/Checkbox.vue'))['default']
    AppInput: (typeof import('@/components/ui/input/Input.vue'))['default']
    AppLabel: (typeof import('@/components/ui/label/Label.vue'))['default']
    AppRadioGroup: (typeof import('@/components/ui/radio-group/RadioGroup.vue'))['default']
    AppRadioGroupItem: (typeof import('@/components/ui/radio-group/RadioGroupItem.vue'))['default']
    AppScrollArea: (typeof import('@/components/ui/scroll-area/ScrollArea.vue'))['default']
    AppScrollBar: (typeof import('@/components/ui/scroll-area/ScrollBar.vue'))['default']
    AppSeparator: (typeof import('@/components/ui/separator/Separator.vue'))['default']
    AppSkeleton: (typeof import('@/components/ui/skeleton/Skeleton.vue'))['default']
    AppSwitch: (typeof import('@/components/ui/switch/Switch.vue'))['default']
    AppTextarea: (typeof import('@/components/ui/textarea/Textarea.vue'))['default']
    AppToggle: (typeof import('@/components/ui/toggle/Toggle.vue'))['default']
    AppToggleGroup: (typeof import('@/components/ui/toggle-group/ToggleGroup.vue'))['default']
    AppToggleGroupItem: (typeof import('@/components/ui/toggle-group/ToggleGroupItem.vue'))['default']
    AppFormField: typeof FormField
    AppFormControl: (typeof import('@/components/ui/form/FormControl.vue'))['default']
    AppFormDescription: (typeof import('@/components/ui/form/FormDescription.vue'))['default']
    AppFormItem: (typeof import('@/components/ui/form/FormItem.vue'))['default']
    AppFormLabel: (typeof import('@/components/ui/form/FormLabel.vue'))['default']
    AppFormMessage: (typeof import('@/components/ui/form/FormMessage.vue'))['default']
    AppPopover: (typeof import('@/components/ui/popover/Popover.vue'))['default']
    AppPopoverContent: (typeof import('@/components/ui/popover/PopoverContent.vue'))['default']
    AppPopoverTrigger: (typeof import('@/components/ui/popover/PopoverTrigger.vue'))['default']
    AppSelect: (typeof import('@/components/ui/select/Select.vue'))['default']
    AppSelectContent: (typeof import('@/components/ui/select/SelectContent.vue'))['default']
    AppSelectGroup: (typeof import('@/components/ui/select/SelectGroup.vue'))['default']
    AppSelectItem: (typeof import('@/components/ui/select/SelectItem.vue'))['default']
    AppSelectItemText: (typeof import('@/components/ui/select/SelectItemText.vue'))['default']
    AppSelectLabel: (typeof import('@/components/ui/select/SelectLabel.vue'))['default']
    AppSelectScrollDownButton: (typeof import('@/components/ui/select/SelectScrollDownButton.vue'))['default']
    AppSelectScrollUpButton: (typeof import('@/components/ui/select/SelectScrollUpButton.vue'))['default']
    AppSelectSeparator: (typeof import('@/components/ui/select/SelectSeparator.vue'))['default']
    AppSelectTrigger: (typeof import('@/components/ui/select/SelectTrigger.vue'))['default']
    AppSelectValue: (typeof import('@/components/ui/select/SelectValue.vue'))['default']
    AppDropdownMenu: (typeof import('@/components/ui/dropdown-menu/DropdownMenu.vue'))['default']
    AppDropdownMenuCheckboxItem: (typeof import('@/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue'))['default']
    AppDropdownMenuContent: (typeof import('@/components/ui/dropdown-menu/DropdownMenuContent.vue'))['default']
    AppDropdownMenuGroup: (typeof import('@/components/ui/dropdown-menu/DropdownMenuGroup.vue'))['default']
    AppDropdownMenuItem: (typeof import('@/components/ui/dropdown-menu/DropdownMenuItem.vue'))['default']
    AppDropdownMenuLabel: (typeof import('@/components/ui/dropdown-menu/DropdownMenuLabel.vue'))['default']
    AppDropdownMenuRadioGroup: (typeof import('@/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue'))['default']
    AppDropdownMenuRadioItem: (typeof import('@/components/ui/dropdown-menu/DropdownMenuRadioItem.vue'))['default']
    AppDropdownMenuSeparator: (typeof import('@/components/ui/dropdown-menu/DropdownMenuSeparator.vue'))['default']
    AppDropdownMenuShortcut: (typeof import('@/components/ui/dropdown-menu/DropdownMenuShortcut.vue'))['default']
    AppDropdownMenuSub: (typeof import('@/components/ui/dropdown-menu/DropdownMenuSub.vue'))['default']
    AppDropdownMenuSubContent: (typeof import('@/components/ui/dropdown-menu/DropdownMenuSubContent.vue'))['default']
    AppDropdownMenuSubTrigger: (typeof import('@/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue'))['default']
    AppDropdownMenuTrigger: (typeof import('@/components/ui/dropdown-menu/DropdownMenuTrigger.vue'))['default']
  }
}

export {}
